### ISSUE TITLE
XML-Nitpicking

### ISSUE THREAD

**Issue by TheComamba** [pfstrack/eldamo#55]
I kinda feel bad about opening an issue for this tiny topic, but I've stumbled over some oddities whilst parsing the xml, and if I were the maintainer, I'd want to be made aware.

The origin marker [ᴹQ] in the ngloss of coron is missing a '.' after the 'Q'.

The ngloss for "farnë" begins with the invisible character U+FE0F, which is used to select variations of an emoji. Same for "finwa" and "yarra". "tildë" has the character between "tip" and "peak".

Is it on purpose that "χarina" and "úχarin" are the only two Later Quenya words spelled with 'χ'? The tengwar rendering suggests an 'h' pronunciation in the first case and a 'ch' in the second case, but the search function on the website seems to treat the character primarily as an 'x'.

**Comment by pfstrack** [comment]
I'm always happy to get feedback, even “nitpicks”.

1. [ᴹQ] >> [ᴹQ.]: I've done a global replacement, which will be pushed with the next release.

2. I've removed the extraneous U+FE0F that you located.

3. These forms have χ because they are apparently Ancient Quenya rather than Modern Quenya.

Anyway, #1 and #2 are not FFNR (Fixed For Next Release)
